name: CI

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: ml-algo
          environment-file: environment.yml
      - name: Install project
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Run linters
        run: |
          black --check .
          isort --check-only .
          ruff check .
      - name: Run unit tests
        run: pytest
